//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeGenerator
    {
        public CodeGenerator()
        {
            this.CodeGeneration_TagModel = new HashSet<CodeGeneration_TagModel>();
        }
    
        public System.Guid CodeGenerationID { get; set; }
        public string CGName { get; set; }
        public string CGDescription { get; set; }
        public int CGCreatedBy { get; set; }
        public string HTMLThatGoesInModal { get; set; }
        public string ScriptThatExecutesUponButtonPress { get; set; }
        public string ScriptThatExecutesOnModalLoad { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Active { get; set; }
        public bool Published { get; set; }
    
        public virtual ICollection<CodeGeneration_TagModel> CodeGeneration_TagModel { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
