//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeGeneration_TagModel
    {
        public int CodeGeneration_Tag_ID { get; set; }
        public string TagName { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.Guid CodeGeneration_Id { get; set; }
    
        public virtual CodeGenerator CodeGenerator { get; set; }
    }
}
