//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGeneration.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.CodeGenerators = new HashSet<CodeGenerator>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int id_user { get; set; }
        public string email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> LastLoggedIn { get; set; }
    
        public virtual ICollection<CodeGenerator> CodeGenerators { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
